spring:
  application:
    name: my-claude
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        model: deepseek-v4-flash
    mcp:
      client:
        stdio:
          servers-configuration: 'classpath:mcp-servers-configuration.json'
logging:
  threshold:
    console: ERROR
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
  config: classpath:logback-spring.xml